### ISSUE TITLE
KB newsletter remarks/todo

### ISSUE THREAD

**Issue by jouvin** [HEP-SF/hep-sf.github.io#1]
Reviewing the draft newsletter proposed by @hegner (https://github.com/HEP-SF/hep-sf.github.io/blob/master/_drafts/nodate-Newsletter-KB.md), I found these minor issues:
* I'd suggest the first part to have title like `HSF Status` as it is confusing to read things that have nothing to do with the main title (KB).
* Second §: `hoping for` instead of `hoping fore`. And there is sort of html comment in the paragraph that is displayed...
* Should the announcement of new versions of ROOT part of the HSF news? May be it would be good to have a section for this in our web site. IMO, this section should be more about "pure" HSF news (else what will be an eligible news from all the HSF-related projects). May be a more HSF-related news could be the started discussions/collaborations between ROOT and WikiToLearn around notebooks for training for example.
* Forthcoming events and job openings: may be add a URL

And we need to add the KB part! Thanks for bootstrapping this!

**Comment by jouvin** [comment]
We also need a section on the logo contest.

**Comment by hegner** [comment]
I hope I addressed your points in my draft. Job openings/events are added automatically on the website.

**Comment by jouvin** [comment]
Closed by #9
