### ISSUE TITLE
GSoC: suggested improvements for managing the projects and organizations

### ISSUE THREAD

**Issue by jouvin** [HEP-SF/hep-sf.github.io#110]
Based on the experience during GSoC 2017 project application phase, it would be nice to streamline a little bit more the management of projects and organizations. In particular, it would be nice to be able to add a project or organization without doing anything else than adding its MD page. Currently, it is still necessary to edit the main page to add it to the list. Also organizations have no description on the organization page, conversely to projects. All these flaws could be easily solved if the organizations and projects were turned into Jekyll collections (one for projects, one for organizations. Then it would be very easy to generate the list from the collection with a small Jekyll template (basically a `for` loop over the projects/organizations if we accept to sort them alphabetically).

Main things to be done are:
- [x] Convert projects and organizations to Jekyll collections
- [x] Generate the project/organization list on the main page with a Jekyll template: this includes adding in the project/organization front-matter an `icon` and a `summary` attribute.
- [x] On the organization page, display before the project list either the `description` attribute if present or the `summary`one (mandatory for the main page). Very similar to what is already done for project in `_includes/gsoc_project.ext`.
- [x] To improve readability on mobile devices, turn into an item list the proposal list built in `_includes/gsoc_project.ext` and `_includes/gsoc_proposal.ext` (to be renamed `_includes/gsoc_organization.ext`).

**Comment by hegner** [comment]
Hi Michel. I agree with your points. We can tackle that for next year as the collection of projects will finish today.

**Comment by jouvin** [comment]
Sure. I have personnally no time to work on it presently... thus this issue to remember what I'd in mind! All these changes should be anyway not intrusive to users (except may be a directory change) and coud be done when we have a bit of spare time.
