### ISSUE TITLE
team.md: check/update startup team member list

### ISSUE THREAD

**Issue by jouvin** [HEP-SF/hep-sf.github.io#13]
We may want to review the team member list in organization/team.md (initially raised in #7).

**Comment by wenaus** [comment]
The definitive member list is the google group membership, if google has a
link to the members (without exposing emails) we can just link that


On Wed, Nov 11, 2015 at 11:23 AM, Michel Jouvin <notifications@github.com>
wrote:

> We may want to review the team member list in organization/team.md
> (initially raised in #7
> <https://github.com/HEP-SF/hep-sf.github.io/pull/7>).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEP-SF/hep-sf.github.io/issues/13>.
>



-- 
-- Torre Wenaus, BNL, ATLAS Experiment  wenaus@gmail.com  wenaus.org/torre
-- BNL: 631 344-4755

**Comment by jouvin** [comment]
After offline discussion, probably no need for this issue...
