### ISSUE TITLE
Invalid URL in proposal_GoInterpreterWagon.md

### ISSUE THREAD

**Issue by jouvin** [HEP-SF/hep-sf.github.io#134]
We are trying to enforce exernal link verification as part of the tests run on the web site. `_gsocproposals/proposal_GoInterpreterWagon.md` contains a reference to an invalid GitHub organization, `https://github.com/gopherds` (only `gopherd` exists but is an empty organization).

The exact error message from the test is:
```
- ./_site/gsoc/proposal_GoInterpreterWagon.html
  *  External link https://github.com/gopherds failed: 404 No error
```
@sbinet please, could you fix it or tell us what is the URL to use. This is a blocking issue for PR #133.

**Comment by sbinet** [comment]
Yeah, the organization was renamed to 'gopherdata' not a long ago.
I'll send a PR.
