### ISSUE TITLE
Please fix CWP papers

### ISSUE THREAD

**Issue by graeme-a-stewart** [HEP-SF/hep-sf.github.io#158]
Hi Mark

In commit 72afdf29 you added two CWP paper links, but you didn't actually add the PDFs to the HSF site, so these are broken links and make Travis look ill for everyone. Can you fix that please?

Thanks

Graeme

**Comment by graeme-a-stewart** [comment]
Ping! Any news on this @msneubauer? Even if you pointed me to where the papers are I can add them to the assets.

**Comment by pelmer** [comment]
It looks like these were "fixed" in the sense that the note was added for one and the other one was removed. I think I saw a different Mark-related problem in the latest travis build: it had an SSL error while trying to connect to the link to Mark's homepage from the Startup Team page.

**Comment by graeme-a-stewart** [comment]
OK, seems this is all good now. Thanks @msneubauer.
