### ISSUE TITLE
Drop down menus don't seem to work properly on iOS

### ISSUE THREAD

**Issue by pelmer** [HEP-SF/hep-sf.github.io#96]
hi, the "Activities", "Communication" and "About" drop-down menus do not seem to work on iOS.
For some odd reason I -am- able to get the "Projects and Support" to open, but the others do not (AFAICT).

**Comment by jouvin** [comment]
Strange... I don't have an iOS device myself so I cannot test... I just tried on Android and it works just fine! In fact very well: the menu is grouped in a "menu button" and the page is much nicely formatted than I thought...

I'll try to see if I have one collegue who has one and could do the test. Is it a new problem or is it the first time you tried?

**Comment by hegner** [comment]
Tested that on Android as well. And there things are indeed fine. Already agreed with Pere (who got an IPhone) to do some debugging together the next days.

**Comment by hegner** [comment]
@pelmer - should work now. Can you test?

**Comment by graeme-a-stewart** [comment]
Ping @pelmer - does it seem to be ok for you now?

**Comment by graeme-a-stewart** [comment]
OK, then I assume this is fixed (in the absence of recent complaints!)
